"""empty message

Revision ID: 0b486fcea628
Revises: f02fa36779f2
Create Date: 2019-03-01 12:33:41.152891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b486fcea628'
down_revision = 'f02fa36779f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('season',
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['show_id'], ['show.show_id'], ),
    sa.PrimaryKeyConstraint('season_id')
    )
    op.create_index(op.f('ix_season_season'), 'season', ['season'], unique=False)
    op.create_table('episode',
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('episode', sa.Integer(), nullable=True),
    sa.Column('downloaded', sa.Boolean(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['season.season_id'], ),
    sa.PrimaryKeyConstraint('episode_id')
    )
    op.create_index(op.f('ix_episode_episode'), 'episode', ['episode'], unique=False)
    op.add_column('show', sa.Column('watching', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'watching')
    op.drop_index(op.f('ix_episode_episode'), table_name='episode')
    op.drop_table('episode')
    op.drop_index(op.f('ix_season_season'), table_name='season')
    op.drop_table('season')
    # ### end Alembic commands ###
