"""empty message

Revision ID: 525391f2a9b4
Revises: 63a9e5c5b00d
Create Date: 2019-03-07 19:05:14.512683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525391f2a9b4'
down_revision = '63a9e5c5b00d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new_show',
    sa.Column('new_show_id', sa.Integer(), nullable=False),
    sa.Column('new_show_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('new_show_id')
    )
    op.create_index(op.f('ix_new_show_new_show_name'), 'new_show', ['new_show_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_new_show_new_show_name'), table_name='new_show')
    op.drop_table('new_show')
    # ### end Alembic commands ###
