"""empty message

Revision ID: 63a9e5c5b00d
Revises: 0b486fcea628
Create Date: 2019-03-01 13:24:52.863913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63a9e5c5b00d'
down_revision = '0b486fcea628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('theTVDB_status', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_show_theTVDB_status'), 'show', ['theTVDB_status'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_show_theTVDB_status'), table_name='show')
    op.drop_column('show', 'theTVDB_status')
    # ### end Alembic commands ###
