"""empty message

Revision ID: 7f8a52b45cc1
Revises: 525391f2a9b4
Create Date: 2019-03-08 14:36:53.615166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f8a52b45cc1'
down_revision = '525391f2a9b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_show_show_name', table_name='show')
    op.create_index(op.f('ix_show_show_name'), 'show', ['show_name'], unique=False)
    op.drop_index('ix_show_theTVDB_name', table_name='show')
    op.create_index(op.f('ix_show_theTVDB_name'), 'show', ['theTVDB_name'], unique=False)
    op.drop_index('ix_show_theTVDB_slug', table_name='show')
    op.create_index(op.f('ix_show_theTVDB_slug'), 'show', ['theTVDB_slug'], unique=False)
    op.drop_index('ix_show_theTVDB_status', table_name='show')
    op.create_index(op.f('ix_show_theTVDB_status'), 'show', ['theTVDB_status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_show_theTVDB_status'), table_name='show')
    op.create_index('ix_show_theTVDB_status', 'show', ['theTVDB_status'], unique=1)
    op.drop_index(op.f('ix_show_theTVDB_slug'), table_name='show')
    op.create_index('ix_show_theTVDB_slug', 'show', ['theTVDB_slug'], unique=1)
    op.drop_index(op.f('ix_show_theTVDB_name'), table_name='show')
    op.create_index('ix_show_theTVDB_name', 'show', ['theTVDB_name'], unique=1)
    op.drop_index(op.f('ix_show_show_name'), table_name='show')
    op.create_index('ix_show_show_name', 'show', ['show_name'], unique=1)
    # ### end Alembic commands ###
