"""empty message

Revision ID: 98e8983c691d
Revises: 
Create Date: 2019-03-19 01:18:30.555808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98e8983c691d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new_show',
    sa.Column('new_show_id', sa.Integer(), nullable=False),
    sa.Column('new_show_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('new_show_id')
    )
    op.create_index(op.f('ix_new_show_new_show_name'), 'new_show', ['new_show_name'], unique=True)
    op.create_table('show',
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('show_name', sa.String(length=64), nullable=True),
    sa.Column('show_dir', sa.String(length=64), nullable=True),
    sa.Column('watching', sa.Boolean(), nullable=True),
    sa.Column('theTVDB_id', sa.Integer(), nullable=True),
    sa.Column('theTVDB_name', sa.String(length=64), nullable=True),
    sa.Column('theTVDB_slug', sa.String(length=64), nullable=True),
    sa.Column('theTVDB_status', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('show_id')
    )
    op.create_index(op.f('ix_show_show_dir'), 'show', ['show_dir'], unique=True)
    op.create_index(op.f('ix_show_show_name'), 'show', ['show_name'], unique=False)
    op.create_index(op.f('ix_show_theTVDB_id'), 'show', ['theTVDB_id'], unique=True)
    op.create_index(op.f('ix_show_theTVDB_name'), 'show', ['theTVDB_name'], unique=False)
    op.create_index(op.f('ix_show_theTVDB_slug'), 'show', ['theTVDB_slug'], unique=False)
    op.create_index(op.f('ix_show_theTVDB_status'), 'show', ['theTVDB_status'], unique=False)
    op.create_table('season',
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['show_id'], ['show.show_id'], ),
    sa.PrimaryKeyConstraint('season_id')
    )
    op.create_index(op.f('ix_season_season'), 'season', ['season'], unique=False)
    op.create_table('episode',
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('episode', sa.Integer(), nullable=True),
    sa.Column('downloaded', sa.Boolean(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('air_date', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['season.season_id'], ),
    sa.PrimaryKeyConstraint('episode_id')
    )
    op.create_index(op.f('ix_episode_air_date'), 'episode', ['air_date'], unique=False)
    op.create_index(op.f('ix_episode_episode'), 'episode', ['episode'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episode_episode'), table_name='episode')
    op.drop_index(op.f('ix_episode_air_date'), table_name='episode')
    op.drop_table('episode')
    op.drop_index(op.f('ix_season_season'), table_name='season')
    op.drop_table('season')
    op.drop_index(op.f('ix_show_theTVDB_status'), table_name='show')
    op.drop_index(op.f('ix_show_theTVDB_slug'), table_name='show')
    op.drop_index(op.f('ix_show_theTVDB_name'), table_name='show')
    op.drop_index(op.f('ix_show_theTVDB_id'), table_name='show')
    op.drop_index(op.f('ix_show_show_name'), table_name='show')
    op.drop_index(op.f('ix_show_show_dir'), table_name='show')
    op.drop_table('show')
    op.drop_index(op.f('ix_new_show_new_show_name'), table_name='new_show')
    op.drop_table('new_show')
    # ### end Alembic commands ###
