"""shows table

Revision ID: f02fa36779f2
Revises: 
Create Date: 2019-02-28 19:31:25.295966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f02fa36779f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show',
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('show_name', sa.String(length=64), nullable=True),
    sa.Column('show_dir', sa.String(length=64), nullable=True),
    sa.Column('theTVDB_id', sa.Integer(), nullable=True),
    sa.Column('theTVDB_name', sa.String(length=64), nullable=True),
    sa.Column('theTVDB_slug', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('show_id')
    )
    op.create_index(op.f('ix_show_show_dir'), 'show', ['show_dir'], unique=True)
    op.create_index(op.f('ix_show_show_name'), 'show', ['show_name'], unique=True)
    op.create_index(op.f('ix_show_theTVDB_id'), 'show', ['theTVDB_id'], unique=True)
    op.create_index(op.f('ix_show_theTVDB_name'), 'show', ['theTVDB_name'], unique=True)
    op.create_index(op.f('ix_show_theTVDB_slug'), 'show', ['theTVDB_slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_show_theTVDB_slug'), table_name='show')
    op.drop_index(op.f('ix_show_theTVDB_name'), table_name='show')
    op.drop_index(op.f('ix_show_theTVDB_id'), table_name='show')
    op.drop_index(op.f('ix_show_show_name'), table_name='show')
    op.drop_index(op.f('ix_show_show_dir'), table_name='show')
    op.drop_table('show')
    # ### end Alembic commands ###
